name: flutter_demo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # 状态管理
  provider: ^6.1.2
  # 屏幕适配相关
  flutter_screenutil: ^5.9.3
  #网络请求
  dio: ^5.4.3+1
  # toast提示
  oktoast: ^3.4.0
  # 获取版本信息设备信息等
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  # 权限申请
  permission_handler: ^11.3.1
  #跳转到外部应用scheme
  url_launcher: ^6.1.6
  #webview
  webview_flutter: ^4.8.0
  #显示html文本
  flutter_html: ^3.0.0-beta.2
  #本地化存储
  shared_preferences: ^2.2.3
  #banner轮播图组件
  flutter_swiper_view: ^1.1.8



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg